### ISSUE TITLE
invalid conversion from 'BaseType_t' {aka 'int'} to 'BaseType_t*' {aka 'int*'}

### ISSUE THREAD

**Issue by levakm1** [Moddingear/HWStepper#1]
Hello, 

I found your library for stepper control, however during compilation of examples I am getting this error: 

/Users/dev365/Development/GitHub/esp32-backend-new/main/HWStepper.cpp: In function 'void HWStepperTimerISR()':
/Users/dev365/Development/esp/esp-idf/components/freertos/include/freertos/projdefs.h:48:52: error: invalid conversion from 'BaseType_t' {aka 'int'} to 'BaseType_t*' {aka 'int*'} [-fpermissive]
 #define pdFALSE                                  ( ( BaseType_t ) 0 )
/Users/dev365/Development/esp/esp-idf/components/freertos/include/freertos/semphr.h:649:130: note: in definition of macro 'xSemaphoreGiveFromISR'
 #define xSemaphoreGiveFromISR( xSemaphore, pxHigherPriorityTaskWoken )    xQueueGiveFromISR( ( QueueHandle_t ) ( xSemaphore ), ( pxHigherPriorityTaskWoken ) )
                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dev365/Development/GitHub/esp32-backend-new/main/HWStepper.cpp:265:43: note: in expansion of macro 'pdFALSE'
   xSemaphoreGiveFromISR(TimingsSemaphore, pdFALSE);
                                           ^~~~~~~
In file included from /Users/dev365/Development/esp/esp-idf/components/freertos/include/freertos/semphr.h:34,
                 from /Users/dev365/Development/GitHub/esp32-backend-new/components/arduino/cores/esp32/Arduino.h:35,
                 from /Users/dev365/Development/GitHub/esp32-backend-new/main/HWStepper.h:1,
                 from /Users/dev365/Development/GitHub/esp32-backend-new/main/HWStepper.cpp:1:
/Users/dev365/Development/esp/esp-idf/components/freertos/include/freertos/queue.h:1400:50: note:   initializing argument 2 of 'BaseType_t xQueueGiveFromISR(QueueHandle_t, BaseType_t*)'
                               BaseType_t * const pxHigherPriorityTaskWoken ) PRIVILEGED_FUNCTION;
                               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

 *  The terminal process "/bin/zsh '-c', 'ninja '" terminated with exit code: 1. 

Can you please advise any way to of it? 

Thank you, 
Michal

**Comment by Moddingear** [comment]
I'll check, the esp32-arduino library has been updated quite a lot since I made that library, so it might work on earlier versions. Anyway, i'll update and fix that!
